import { HealthResponse } from "@/lib/fpl/types";
import ModelBadge from "./ModelBadge";

interface FooterProps {
  health: HealthResponse | null;
}

export default function Footer({ health }: FooterProps) {
  return (
    <footer className="mt-12 pb-8">
      <hr className="fpl-double-rule max-w-lg mx-auto" />
      <div className="text-center space-y-3">
        {health && <ModelBadge health={health} />}
        <p className="text-sm text-[#7A6E5D] font-[family-name:var(--font-lora)] italic">
          Predictions generated by a Random Forest model trained on 2024/25 season data.
          <br />
          Data sourced from the official Fantasy Premier League API.
        </p>
      </div>
    </footer>
  );
}
